# Colors Plugin yml
name: Colors
main: com.severalcircles.colors.Main
version: Red01
authors: ["Several Circles", "Minotaur", "Beeg Mo"]

commands:
  about:
    description: Outputs information about the plugin including its version number.
    usage: /<command>
