# Colors Plugin yml
name: Colors
main: com.severalcircles.colors.Main
version: Red02
authors: ["Several Circles", "Minotaur", "Beeg Mo"]

commands:
  about:
    description: Outputs information about the plugin including its version number.
    usage: /<command>

  persona:
    description: Spams chat down with "Joker Persona" 3000 times.
    usage: /<command>

  sans:
    description: Spawns a skeleton on a player.
    usage: /<command> <player>

permissions:
  com.severalcircles.colors.sans:
    description: Allows you to give a player a bad time by sending a skeleton to their position because it's funny sans.
    default: op